### ISSUE TITLE
Cannot reproduce CCA results as computed from PMA package

### ISSUE THREAD

**Issue by JohannesWiesner** [Teekuningas/pypma#2]
First of all, thank you very much for implementing the sparse CCA from Witten et al.! As a  python user, I would be glad if I would not have to switch programming languages but be able to write one analysis pipeline purely in python. Besides, your code would allow me to integrate [your CCA function](https://github.com/Teekuningas/sparsecca/blob/6f3b0758f43263adb6f332f93413ea0830a52acb/sparsecca/_cca_pmd.py#L75) into a scikit-learn pipeline. I have one question though: I was trying to reproduce the example from Witten et al. as described [on page 7 of their documentation ](https://cran.r-project.org/web/packages/PMA/PMA.pdf) but couldn't get the same results. I am not a math expert so I cannot really explain what might cause these deviations. Maybe I also did not use the exact same parameters? The only obvious difference between your package and the PMA package is, that your function [only demeans x and z ](https://github.com/Teekuningas/sparsecca/blob/6f3b0758f43263adb6f332f93413ea0830a52acb/sparsecca/_cca_pmd.py#L86-L88) while Witten et al. [use z-standardization ](https://github.com/bnaras/PMA/blob/e36a23c506b17be03d23c547075ac134861f7ba0/R/CCA.R#L209-L216). But I don't think that this drives the deviation?

Here's the code from Witten et al.:

```R
## Run example from PMA package ################################################

# first, do CCA with type="standard"
# A simple simulated example
set.seed(3189)
u <- matrix(c(rep(1,25),rep(0,75)),ncol=1)
v1 <- matrix(c(rep(1,50),rep(0,450)),ncol=1)
v2 <- matrix(c(rep(0,50),rep(1,50),rep(0,900)),ncol=1)
x <- u%*%t(v1) + matrix(rnorm(100*500),ncol=500)
z <- u%*%t(v2) + matrix(rnorm(100*1000),ncol=1000)

# Can run CCA with default settings, and can get e.g. 3 components
out <- CCA(x,z,typex="standard",typez="standard",K=3)

## Save x,z and canonical weights as .txt files 
write.table(x,file="x.txt",row.names=F,col.names=F)
write.table(z,file="z.txt",row.names=F,col.names=F)
write.table(out$u,file="out_u.txt",row.names=F,col.names=F)
write.table(out$v,file="out_v.txt",row.names=F,col.names=F)
```

And here's me trying to reproduce the canonical weights:

```python
import numpy as np
from sparsecca._cca_pmd import cca
import matplotlib.pyplot as plt

# load x and z from PMA example
x = np.loadtxt('./x.txt')
z = np.loadtxt('./z.txt')

# load canonical weights produced by PMA package
out_u = np.loadtxt('./out_u.txt')
out_v = np.loadtxt('./out_v.txt')

# run cca one more time with sparsecca package and the same settings as used
# in the pma package NOTE: Although documentation of PMA package says that the 
# penalties are NULL as default, it does not seem to be the case. 
# Instead 0.3 seems to be the default value for both x and z.
u,v,d = cca(x,z,penaltyx=0.3,penaltyz=0.3,K=3,niter=15)

# check canonical weights from PMA package against sparsecca package
print(np.array_equal(out_u,u))
print(np.array_equal(out_v,v))

# plot distribution of deviations (ignore zeros for plotting purposes)
deviations = np.abs(out_u-u).flatten()
deviations = deviations[deviations != 0]
plt.hist(deviations)
```
![image](https://user-images.githubusercontent.com/48254290/143079110-c0177c18-2c24-4584-ae32-ca4d49b1e23a.png)

As you can see most of the canonical weights only have small deviations, but there are a few that are quite different between the python implementation and the PMA package.

**Comment by teekuningas** [comment]
Hello, thanks for bringing up the issue! Can you try running:

```
import numpy as np
from sparsecca._cca_pmd import cca
import matplotlib.pyplot as plt

# load x and z from PMA example
x = np.loadtxt('./x.txt')
z = np.loadtxt('./z.txt')

# load canonical weights produced by PMA package
out_u = np.loadtxt('./out_u.txt')
out_v = np.loadtxt('./out_v.txt')

x = (x - np.mean(x, axis=0)[np.newaxis, :]) / np.std(x, axis=0, ddof=1)[np.newaxis, :]
z = (z - np.mean(z, axis=0)[np.newaxis, :]) / np.std(z, axis=0, ddof=1)[np.newaxis, :]

# run cca one more time with sparsecca package and the same settings as used
# in the pma package NOTE: Although documentation of PMA package says that the 
# penalties are NULL as default, it does not seem to be the case. 
# Instead 0.3 seems to be the default value for both x and z.
u,v,d = cca(x,z,penaltyx=0.3,penaltyz=0.3,K=3,niter=15, standardize=False)

if np.allclose(u, -out_u):
    u = -u
    v = -v

# check canonical weights from PMA package against sparsecca package
print(np.array_equal(out_u,u))
print(np.array_equal(out_v,v))

# plot distribution of deviations (ignore zeros for plotting purposes)
deviations = np.abs(out_u-u).flatten()
deviations = deviations[deviations != 0]
plt.hist(deviations)
```

That is, as you brought up, try similar standardization. Do the weights get similar enough?

I think I'll have to change the standardization so that the results match with the default values!

**Comment by JohannesWiesner** [comment]
I will try out later today and let you know :)

**Comment by teekuningas** [comment]
I edited it a bit, now the np.std() at standardization uses correct ddof.

Also I added the following to make the signs comparable (there's no real reason why the signs should be the same, right? As long as they are pairwise consistent..):

```
if np.allclose(u, -out_u):
    u = -u
    v = -v
```

Finally the numbers still do not exactly match. But this, I guess, comes from saving and reading from the file between python and R.

In R we have:
```
> sprintf("%.20f",x[1,1])
[1] "0.15371921571790780892"
```
In python we have:
```
(Pdb) x[0,0]
0.153719215717908
```

The deviations now seem to be under 1e-12, which is comparable to inaccuracies at the beginning..?

Thanks : ]

**Comment by JohannesWiesner** [comment]
Ha! Very nice! Thansk for the super quick implementation! I tested your code on my machine and it works! :)

> Finally the numbers still do not exactly match. But this, I guess, comes from saving and reading from the file between python and R.

Yes you're right, of course one will never be able to produce the exact same numbers due to floating point errors and because of the I/O part when exchanging data. I updated my example by using the `.feather` format. That at least might reduce numerical errors when it comes to the I/O part. I am not a data engineer but it seems that the is the state-of-the-art exchange format when one wants to exchange data between python an R (it seems to be developed by [both Python and R core developers](https://www.rstudio.com/blog/feather/) so I guess that's a good indicator). 

Here are my updated scripts:

```R
## Run example from PMA package ################################################

library(PMA)
library(feather)

# first, do CCA with type="standard"
# A simple simulated example
set.seed(3189)
u <- matrix(c(rep(1,25),rep(0,75)),ncol=1)
v1 <- matrix(c(rep(1,50),rep(0,450)),ncol=1)
v2 <- matrix(c(rep(0,50),rep(1,50),rep(0,900)),ncol=1)
x <- u%*%t(v1) + matrix(rnorm(100*500),ncol=500)
z <- u%*%t(v2) + matrix(rnorm(100*1000),ncol=1000)

# Can run CCA with default settings, and can get e.g. 3 components
out <- CCA(x,z,typex="standard",typez="standard",K=3,penaltyx=0.3,penaltyz=0.3)

# Save x,z and canonical weights as in .feather format (feather only supports
# data frames)
x_df <- data.frame(x)
z_df <- data.frame(z)
out_u_df <- data.frame(out$u)
out_v_df <- data.frame(out$v)

write_feather(x_df,path="x_df.feather")
write_feather(z_df,path="z_df.feather")
write_feather(out_u_df,path="out_u_df.feather")
write_feather(out_v_df, path="out_v_df.feather")
```

and then:

```python
import numpy as np
import pandas as pd
from sparsecca._cca_pmd import cca
import matplotlib.pyplot as plt

# load x, z and canonical weights for u and v as produced by PMA package example
# feather only supports data frames 
x_df = pd.read_feather('./x_df.feather')
z_df = pd.read_feather('./z_df.feather')
out_u_df = pd.read_feather('./out_u_df.feather')
out_v_df = pd.read_feather('./out_v_df.feather')
x = x_df.values
z = z_df.values
out_u = out_u_df.values
out_v = out_v_df.values

# standardize x and v in the same way as PMA package does
# FIXME: This way of standardization should be included in the sparsecca package
x = (x - np.mean(x, axis=0)[np.newaxis, :]) / np.std(x, axis=0, ddof=1)[np.newaxis, :]
z = (z - np.mean(z, axis=0)[np.newaxis, :]) / np.std(z, axis=0, ddof=1)[np.newaxis, :]

# run cca one more time with sparsecca package and the same settings as used
# in the pma package
# FIXME: Once standardization is fixed in sparsecca package, standardization
# can be set to True
u,v,d = cca(x,z,penaltyx=0.3,penaltyz=0.3,K=3,niter=15,standardize=False)

# check canonical weights of both variates from PMA package against sparsecca 
# package
print(np.allclose(np.abs(u),np.abs(out_u)))
print(np.allclose(np.abs(v),np.abs(out_v)))

# plot distribution of deviations (ignore zeros for plotting purposes)
deviations = np.abs(u)-np.abs(out_u)
deviations = deviations.flatten()
deviations = deviations[deviations != 0]
plt.hist(deviations)
```

> Also I added the following to make the signs comparable (there's no real reason why the signs should be the same, right? As long as they are pairwise consistent..):
> 
> if np.allclose(u, -out_u):
>     u = -u
>     v = -v

Sure, you're right, the signs might change. I don't really get your lines of code though, but I guess they are doing the same as those lines?:

```
print(np.allclose(np.abs(u),np.abs(out_u)))
print(np.allclose(np.abs(v),np.abs(out_v)))
```

One could also think about using those scripts to implement a test in your repository :) I guess it could be possible to use a conda environment with `python`, `R` and/or `rpy2` and run these scripts as tests :)

**Comment by teekuningas** [comment]
Glad that it worked out : ] 

And yes, it's a great idea. I added one!

https://github.com/Teekuningas/sparsecca/pull/3/commits/6df9f1286298be9bbf24309b0c251f3261462e2b

Does it look fine?

Did not actually know that using R from Python is so easy. But I'm sure there are good reasons for having python-only implementation (instead of a wrapper), debugging comes first to mind..

**Comment by JohannesWiesner** [comment]
Looks good to me! Just tested it on my machine :) 

> Did not actually know that using R from Python is so easy. But I'm sure there are good reasons for having python-only implementation (instead of a wrapper), debugging comes first to mind..

Yeah, I am also still skeptical about rpy2, but I think it's getting more and more popular. And definitely debugging is a problem, so it's really a good thing that you implemented the code in Python :) 

As for rpy2 I also couldn't get it to run the first time, when I cloned my base environment on conda (I have a Windows Machine and the rpy2 folks say that often this causes problems). Just for transparency, the following minimum implementation worked for me (based on this [StackOverflow post](https://stackoverflow.com/questions/61622624/how-to-correctly-set-up-rpy2)):

```
conda create -n rpy2-env r-essentials r-base python=3.7
conda activate rpy2-env
conda install -c r rpy2
conda install -c anaconda numpy pandas scipy
```
I guess with this one could build a light-weight miniconda environment that is then used to run the test scripts :)

**Comment by teekuningas** [comment]
I, too, often have problems with conda's versions of compilers and linkers. Thus I often work with just system python and venv..

However, your environment seems to work fine for me too : ]

**Comment by JohannesWiesner** [comment]
Nice! For example, rpy2 doesn't seem to run with the latest python version so this is why I set it to v3.7. So there you go, rpy2 still is not that developed yet for really safe use ;)

**Comment by fabioboh** [comment]
@Teekuningas @JohannesWiesner I also just read this thread, which I also found very useful, so thank to you both!
